### PR TITLE
typescript-types

### PR DESCRIPTION
**Pull request by wpdas**
Typescript types were included to be used in TS projects.

### CODE REVIEW

**Review by rishichawda — APPROVED** [review]

**Comment by rishichawda** [comment]
Hi @Wpdas. Thanks for your contribution! Added in the new release [v1.2.2](https://github.com/rishichawda/react-native-qrcode-generator/releases/tag/v1.2.2)  🎉.

PS: On a side note, while contributing to other repositories, please check the allow edits from collaborators/owners of the repository so that it could be easier to make some one-line changes quickly. 😄

**Comment by wpdas** [comment]
Hi @rishichawda. You're welcome. Sorry man, where is this information (allow edits)?

**Comment by rishichawda** [comment]
You should be able to see it while creating the pull request - in the section on the right. [Here's the wiki](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by wpdas** [comment]
Thanks, sorry for that haha.

**Comment by rishichawda** [comment]
No problem.

**Pull request merged**
